const fs = require("fs");
const path = require("path");
const { transformSync } = require("@swc/core");

const ROOT_DIR = path.resolve(__dirname, "..", "..");
const DIST_DIR = path.join(ROOT_DIR, "dist");
const OUTPUT_DIR = path.join(ROOT_DIR, "website", "src", "generated");
const OUTPUT_FILE = path.join(OUTPUT_DIR, "sandpackLocalEngine.ts");
const PACKAGE_JSON_PATH = path.join(ROOT_DIR, "package.json");

const toPosix = (value) => value.split(path.sep).join("/");

const collectDistFiles = (directory) => {
	const entries = fs.readdirSync(directory, { withFileTypes: true });
	const files = [];

	for (const entry of entries) {
		const fullPath = path.join(directory, entry.name);
		if (entry.isDirectory()) {
			files.push.apply(files, collectDistFiles(fullPath));
			continue;
		}

		if (!entry.name.endsWith(".js")) {
			continue;
		}

		files.push(fullPath);
	}

	return files.sort();
};

const buildPackageManifest = () => {
	const packageJson = JSON.parse(fs.readFileSync(PACKAGE_JSON_PATH, "utf8"));
	return JSON.stringify(
		{
			name: packageJson.name,
			version: packageJson.version,
			main: "./index.js",
			exports: {
				".": "./index.js",
				"./package.json": "./package.json",
				"./*": "./*",
			},
		},
		null,
		2,
	);
};

const normalizeRelativeSegments = (value) => {
	const normalized = value.split("/");
	const result = [];

	for (const segment of normalized) {
		if (!segment || segment === ".") {
			continue;
		}

		if (segment === "..") {
			result.pop();
			continue;
		}

		result.push(segment);
	}

	return result.join("/");
};

const resolveEngineImportSpecifier = (
	jsPaths,
	fromRelativePath,
	specifier
) => {
	if (!specifier.startsWith(".")) {
		return specifier;
	}

	const fromDirectory = fromRelativePath.includes("/")
		? fromRelativePath.slice(0, fromRelativePath.lastIndexOf("/"))
		: "";
	const joinedPath = fromDirectory
		? `${fromDirectory}/${specifier}`
		: specifier;
	const normalizedPath = normalizeRelativeSegments(joinedPath);

	if (jsPaths.has(`${normalizedPath}.js`)) {
		return `${specifier}.js`;
	}

	if (jsPaths.has(`${normalizedPath}/index.js`)) {
		return `${specifier}/index.js`;
	}

	return specifier;
};

const rewriteEngineModule = (jsPaths, code, fromRelativePath) => {
	const fromPattern = /(from\s+["'])(\.{1,2}(?:\/[^"']+)?)(["'])/g;
	const sideEffectPattern = /(import\s+["'])(\.{1,2}(?:\/[^"']+)?)(["'])/g;
	const rewrite = (_match, prefix, specifier, suffix) => {
		return `${prefix}${resolveEngineImportSpecifier(
			jsPaths,
			fromRelativePath,
			specifier
		)}${suffix}`;
	};

	return code.replace(fromPattern, rewrite).replace(sideEffectPattern, rewrite);
};

const buildEngineModule = (jsPaths, filePath) => {
	const relativeDistPath = toPosix(path.relative(DIST_DIR, filePath));
	const rawCode = fs.readFileSync(filePath, "utf8");
	const sanitizedCode = rewriteEngineModule(
		jsPaths,
		rawCode,
		relativeDistPath
	)
		.replace(/^\/\/# sourceMappingURL=.*$/gm, "")
		.trimEnd();

	return transformSync(sanitizedCode, {
		filename: relativeDistPath,
		sourceMaps: false,
		jsc: {
			target: "es2019",
		},
		module: {
			type: "commonjs",
		},
	}).code.trimEnd();
};

const buildOutput = () => {
	const distFiles = collectDistFiles(DIST_DIR);
	const manifest = buildPackageManifest();
	const jsPaths = new Set(
		distFiles.map((filePath) => toPosix(path.relative(DIST_DIR, filePath)))
	);
	const lines = [];

	lines.push("// Auto-generated by website/scripts/generateSandpackLocalEngine.cjs");
	lines.push("// Do not edit by hand.");
	lines.push("");
	lines.push(
		`const LOCAL_ENGINE_PACKAGE_JSON = ${JSON.stringify(`${manifest}\n`)};`
	);
	lines.push("");
	lines.push("export const SANDPACK_LOCAL_ENGINE_FILES = {");
	lines.push('\t"/node_modules/sliver-engine/package.json": {');
	lines.push("\t\tcode: LOCAL_ENGINE_PACKAGE_JSON,");
	lines.push("\t\thidden: true,");
	lines.push("\t\treadOnly: true,");
	lines.push("\t},");

	distFiles.forEach((filePath) => {
		const relativeDistPath = toPosix(path.relative(DIST_DIR, filePath));
		lines.push(`\t"/node_modules/sliver-engine/${relativeDistPath}": {`);
		lines.push(
			`\t\tcode: ${JSON.stringify(buildEngineModule(jsPaths, filePath))},`
		);
		lines.push("\t\thidden: true,");
		lines.push("\t\treadOnly: true,");
		lines.push("\t},");
	});

	lines.push("} as const;");
	lines.push("");

	return `${lines.join("\n")}\n`;
};

fs.mkdirSync(OUTPUT_DIR, { recursive: true });
fs.writeFileSync(OUTPUT_FILE, buildOutput(), "utf8");
console.log(`[sandpack-engine] Wrote ${path.relative(ROOT_DIR, OUTPUT_FILE)}`);
