import { Vector } from "sliver-engine";

export const ENCLOSURE_BORDER_COLOR = "#334155";

export const ENCLOSURE_LEFT = 20;
export const ENCLOSURE_TOP = 20;
export const ENCLOSURE_THICKNESS = 16;
export const ENCLOSURE_OUTER_WIDTH = 440;
export const ENCLOSURE_OUTER_HEIGHT = 224;

export const ENCLOSURE_CEILING_POSITION = new Vector(ENCLOSURE_LEFT, ENCLOSURE_TOP);
export const ENCLOSURE_HORIZONTAL_SIZE = new Vector(
	ENCLOSURE_OUTER_WIDTH,
	ENCLOSURE_THICKNESS,
);

export const ENCLOSURE_FLOOR_POSITION = new Vector(
	ENCLOSURE_LEFT,
	ENCLOSURE_TOP + ENCLOSURE_OUTER_HEIGHT - ENCLOSURE_THICKNESS,
);

export const ENCLOSURE_LEFT_WALL_POSITION = new Vector(
	ENCLOSURE_LEFT,
	ENCLOSURE_TOP + ENCLOSURE_THICKNESS,
);

export const ENCLOSURE_RIGHT_WALL_POSITION = new Vector(
	ENCLOSURE_LEFT + ENCLOSURE_OUTER_WIDTH - ENCLOSURE_THICKNESS,
	ENCLOSURE_TOP + ENCLOSURE_THICKNESS,
);

export const ENCLOSURE_VERTICAL_SIZE = new Vector(
	ENCLOSURE_THICKNESS,
	ENCLOSURE_OUTER_HEIGHT - ENCLOSURE_THICKNESS * 2,
);
